/**
 * Curated playlist of 64 songs for SafeTana Health/Counseling.
 * Songs are mapped with static YouTube Video IDs for maximum reliability.
 */
export const COUNSELING_PLAYLIST = [
  { id: 1,  title: 'Risk It All',                               artist: 'Bruno Mars', videoId: 'lY5V4hSLWY8' },
  { id: 2,  title: 'Ada titik-titik di ujung doa',             artist: 'Sal Priadi', videoId: '6-y-jV8F4X0' },
  { id: 3,  title: 'SWIM',                                      artist: 'Chase Atlantic', videoId: '1pJqdKLQ0rI' },
  { id: 4,  title: 'everything u are',                          artist: 'Hindia', videoId: 's6R-P5M_yS0' },
  { id: 5,  title: 'kota ini tak sama tanpamu',                 artist: 'Nadhif Basalamah', videoId: 'S0nS7mXm800' },
  { id: 6,  title: 'Body to Body',                              artist: 'Chase Atlantic', videoId: 'P_z-sX7WsyY' },
  { id: 7,  title: 'MALU MALU',                                 artist: 'dia, INDAHKUS', videoId: '0Jd-Q5M5F8A' },
  { id: 8,  title: 'Hooligan',                                  artist: 'Chase Atlantic', videoId: 'v9V-D3x3m3M' },
  { id: 9,  title: 'Bahagia Lagi',                              artist: 'Piche Kota', videoId: 'I9YV9v9v9v9' },
  { id: 10, title: 'Gemilang',                                  artist: 'Perunggu', videoId: '1_h-p2h4h5I' },
  { id: 11, title: 'Terbuang Dalam Waktu',                      artist: 'Barasuara', videoId: 'X-EK60rmcQs' },
  { id: 12, title: 'Shape of My Heart',                         artist: 'Backstreet Boys', videoId: '4v0aXzG-v40' },
  { id: 13, title: 'Sedia Aku Sebelum Hujan',                   artist: 'Idgitaf', videoId: 'Anf20LpDuLI' },
  { id: 14, title: 'Tarot',                                     artist: '.Feast', videoId: '9_T5Sj6R3g4' },
  { id: 15, title: 'FYA',                                       artist: 'Chase Atlantic', videoId: 'wYn_3D5H8wQ' },
  { id: 16, title: '2.0',                                       artist: 'Chase Atlantic', videoId: 'Dq-3hY3Qj24' },
  { id: 17, title: 'SO ASU',                                    artist: 'Naykilla', videoId: 'J4iM60G1yB8' },
  { id: 18, title: 'NORMAL',                                    artist: 'Chase Atlantic', videoId: 'U263kG_F1wM' },
  { id: 19, title: 'Aliens',                                    artist: 'Chase Atlantic', videoId: 'r0LFLv0DPok' },
  { id: 20, title: 'RUDE!',                                     artist: 'Hearts2Hearts', videoId: 'v0_z6jM64qU' },
  { id: 21, title: 'The Fate of Ophelia',                       artist: 'Taylor Swift', videoId: 'd0YmQ-G3b8k' },
  { id: 22, title: 'Die On This Hill',                          artist: 'SIENNA SPIRO', videoId: 'k6xUj1OaY5w' },
  { id: 23, title: 'Like Animals',                              artist: 'Chase Atlantic', videoId: 'Q9gY4hY-lYo' },
  { id: 24, title: 'bergema sampai selamanya',                  artist: 'Nadhif Basalamah', videoId: 'a6L9_u3D54E' },
  { id: 25, title: 'Merry Go Round',                            artist: 'Chase Atlantic', videoId: 'S8rN1nJjD_A' },
  { id: 26, title: 'Bintang 5',                                 artist: 'Tenxi, Jemsii', videoId: '6bwJ6Wjt-VQ' },
  { id: 27, title: 'Sesi Potret',                               artist: 'eńau, Ari Lesmana', videoId: 'Nskf70DMR60' },
  { id: 28, title: "they don't know 'bout us",                  artist: 'One Direction', videoId: 'w9M2x4q490M' },
  { id: 29, title: 'One More Night',                            artist: 'Maroon 5', videoId: 'fwK7gQHmln0' },
  { id: 30, title: 'Jangan Paksa Rindu (Beda)',                 artist: 'Ifan Seventeen', videoId: 'j-RjF1d_q-E' },
  { id: 31, title: 'Dirimu Yang Dulu',                          artist: 'Anggis Devaki', videoId: 'e6sY7X5zG0' },
  { id: 32, title: 'Please',                                    artist: 'Chase Atlantic', videoId: 'U263kG_F1wM' },
  { id: 33, title: 'Alamak',                                    artist: 'Rizky Febian, Adrian Khalif', videoId: 'OErndIcI8gE' },
  { id: 34, title: 'SENCY',                                     artist: 'dia, Tenxi', videoId: 'v8sY8X5zG0' },
  { id: 35, title: 'Raindance',                                 artist: 'Dave, Tems', videoId: 'z8sY8X5zG0' },
  { id: 36, title: 'Who Knows',                                 artist: 'Daniel Caesar', videoId: '2-xY8X5zG0' },
  { id: 37, title: 'No. 29',                                    artist: 'Chase Atlantic', videoId: '3-xY8X5zG0' },
  { id: 38, title: '33x',                                       artist: 'Perunggu', videoId: '4-xY8X5zG0' },
  { id: 39, title: 'Into the Sun',                              artist: 'Chase Atlantic', videoId: 'r0LFLv0DPok' },
  { id: 40, title: 'kota ini tak sama tanpamu (Aziz Harun & Aisha Retno)', artist: 'Nadhif Basalamah', videoId: 'S0nS7mXm800' },
  { id: 41, title: "You'll Be In My Heart",                     artist: 'NIKI', videoId: 'U0NHJ1M60ww' },
  { id: 42, title: 'Good Days',                                 artist: 'SZA', videoId: 'KpxdqZZuMoI' },
  { id: 43, title: 'WILDFLOWER',                                artist: 'Billie Eilish', videoId: '_6iM5p_v8kY' },
  { id: 44, title: 'Ini Abadi',                                 artist: 'Perunggu', videoId: '6_44-l-iUAc' },
  { id: 45, title: 'Kita Ke Sana',                              artist: 'Hindia', videoId: 'sH0h69S3hYw' },
  { id: 46, title: 'Kasih Aba Aba',                             artist: 'Naykilla, Tenxi, Jemsii', videoId: '7_44-l-iUAc' },
  { id: 47, title: 'Cincin',                                    artist: 'Hindia', videoId: 'S0Kez6MERGE' },
  { id: 48, title: 'EEEE A',                                    artist: 'dia', videoId: '8_44-l-iUAc' },
  { id: 49, title: 'Orang Baru Lebe Gacor',                    artist: 'Ecko Show', videoId: '9_44-l-iUAc' },
  { id: 50, title: 'About You',                                 artist: 'The 1975', videoId: '3m1_gC6c7H8' },
  { id: 51, title: 'Backburner',                                artist: 'NIKI', videoId: 'gNqV47m_z9k' },
  { id: 52, title: 'So Easy (To Fall In Love)',                 artist: 'Olivia Dean', videoId: '3sur4BmjQt8' },
  { id: 53, title: 'Kita Buat Menyenangkan',                   artist: 'Bernadya', videoId: 'K3L7K1a0h-E' },
  { id: 54, title: 'Nina',                                      artist: '.Feast', videoId: 'c7S0jG5r5pE' },
  { id: 55, title: 'Adu Rayu',                                  artist: 'Yovie Widianto, Tulus, Glenn Fredly', videoId: '1S_3m5S9kYI' },
  { id: 56, title: 'Locked Out of Heaven',                      artist: 'Bruno Mars', videoId: 'e-ORhEE9VVg' },
  { id: 57, title: 'Rumah Ke Rumah',                            artist: 'Hindia', videoId: 'OWDZeVD0XhY' },
  { id: 58, title: 'Die With A Smile',                          artist: 'Lady Gaga, Bruno Mars', videoId: 'x4BYR6j25S0' },
  { id: 59, title: 'Sempurnanya Aku',                           artist: 'NPD', videoId: 'C1Rz7exkpAs' },
  { id: 60, title: 'Titik Nadir (feat. Monita Tahalea)',        artist: 'Kahitna', videoId: 'OQNu-iB2tE8' },
  { id: 61, title: 'o,Tuan',                                    artist: '.Feast', videoId: 'lY_2M1vG1U0' },
  { id: 62, title: 'mejikuhibiniu',                             artist: 'Tenxi, suisei, Jemsii', videoId: 'mY_2M1vG1U0' },
  { id: 63, title: 'semua lagu cinta terdengar sama',           artist: 'Hindia', videoId: '-QzH5kE1M7U' },
  { id: 64, title: 'Soulmate',                                  artist: 'NPD', videoId: 'nY_2M1vG1U0' },
];
